name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  unit-test:
    name: unit test
    runs-on: ubuntu-24.04
    env:
      FORCE_COLOR: 1
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.18.4"
            otp: "28.0"
            lint: lint
          - elixir: "1.17.3"
            otp: "27.3"
          - elixir: "1.17.3"
            otp: "26.2"
          - elixir: "1.17.3"
            otp: "25.3"
          - elixir: "1.14.5"
            otp: "24.3"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore deps and _build cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-
      - name: Install dependencies
        run: mix deps.get
      - name: Compile deps
        run: mix deps.compile
      - name: Check unused dependencies
        run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}
      - name: Compile lint
        run: mix compile --warning-as-errors
        if: ${{ matrix.lint }}
      - name: Run tests
        run: mix test

  integration-test:
    name: integration test
    runs-on: ubuntu-24.04
    env:
      FORCE_COLOR: 1
    strategy:
      fail-fast: false
      matrix:
        elixirbase:
          - "1.18.4-erlang-28.0.2-alpine-3.22.1"
          - "1.17.3-erlang-27.3.4.2-alpine-3.22.1"
          - "1.17.3-erlang-26.2.5.14-alpine-3.22.1"
          - "1.17.3-erlang-25.3.2.21-alpine-3.22.1"
          - "1.14.5-erlang-24.3.4.17-alpine-3.22.1"
    steps:
      - uses: earthly/actions-setup@v1
      - uses: actions/checkout@v4
      - name: ecto integration-test under ${{matrix.elixirbase}}
        run: earthly -P --ci --build-arg ELIXIR_BASE=${{matrix.elixirbase}} +integration-test
